;;打印一个点的坐标
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))
;;线段 由起点和终点构成
(define (make-sagment start-point end-point)
  (cons start-point end-point))
;;起点
(define (start-sagment sagment)
  (car sagment))
;;终点
(define (end-sagment sagment)
  (cdr sagment))
(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (average x y)
  (/ (+ x y)
     2))
(define (average-of-point start-point end-point)
  (make-point (average (x-point start-point)(x-point end-point))
              (average (y-point start-point)(y-point end-point))))
(define (midpoint-sagment sagment)
  (let ((st-sagment (start-sagment sagment))
    (ed-sagment (end-sagment sagment)))
    (average-of-point st-sagment ed-sagment)))